#!/bin/bash
#
# Reduce size of OTP by removing beam files that are not needed.
#
# $Id: wings_reduce_otp,v 1.2 2003/08/17 10:30:08 bjorng Exp $
#

erl_top=$1
stdlib=$erl_top/lib/stdlib-*
kernel=$erl_top/lib/kernel-*

#
# Remove files not needed in kernel and stdlib. Be conservative.
#
td=$kernel/ebin
rm -rf $td/kernel.app
rm -rf $td/kernel.appup

# The pre-loaded files are not needed.
rm -rf $td/otp_ring0.beam
rm -rf $td/init.beam
rm -rf $td/erl_prim_loader.beam
rm -rf $td/prim_file.beam
rm -rf $td/prim_init.beam

# In R9C, erlang.beam is also pre-loaded.
rm -rf $td/erlang.beam

# No need for IPv6, socks, or erl_boot_server.
rm -rf $td/inet6_tcp.beam
rm -rf $td/inet6_tcp_dist.beam
rm -rf $td/inet6_udp.beam
rm -rf $td/socks5.beam
rm -rf $td/socks5_auth.beam
rm -rf $td/socks5_tcp.beam
rm -rf $td/socks5_udp.beam
rm -rf $td/erl_boot_server.beam

# Stdlib
td=$stdlib/ebin
rm -rf $td/stdlib.app
rm -rf $td/stdlib.appup

# Used to be part of stdlib; no longer the case in R9C.
rm -rf $td/erl_id_trans.beam

# Only used by erlc.
rm -rf $td/erl_compile.beam

# Only used by the compiler.
rm -rf $td/ms_transform.beam

# No use in Wings.
rm -rf $td/beam_lib.beam
